import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { UserRound, GraduationCap, Building2, LockKeyhole, ArrowRight, ShieldCheck } from 'lucide-react';
import { login, register } from '../../services/authService';
import { BRANCHES } from '../../utils/constants';
import { required, password as validatePassword } from '../../utils/validators';
import './Login.css';

export default function Login(){const nav=useNavigate();const [mode,setMode]=useState('login');const [form,setForm]=useState({name:'',prn:'',branch:'',password:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const change=(k,v)=>setForm(f=>({...f,[k]:v}));const submit=async e=>{e.preventDefault();setError('');try{required(form.name,'Player name');required(form.prn,'PRN');required(form.branch,'Engineering branch');validatePassword(form.password);setBusy(true);const fn=mode==='login'?login:register;await fn(form);nav('/levels');}catch(err){setError(err.message)}finally{setBusy(false)}};return <main className="login-page"><div className="login-bg"/><div className="login-grid"/><header className="login-brand"><div><strong><span>TECH</span> RUNNER</strong><small>CODE • RUN • SURVIVE • WIN</small></div><div className="status"><i/> EVENT ONLINE <small>PLAY &gt; LEARN &gt; COMPETE</small></div></header><section className="login-layout"><aside className="login-aside"><p>RUN<br/>LEARN<br/>COMPETE<br/>LEVEL UP</p><div className="runner-mark">◢</div><b>BUILD SKILLS<br/>FOR A BETTER<br/>TOMORROW</b></aside><form className="login-card" onSubmit={submit}><div className="card-line"/><div className="card-heading"><span/><h1>{mode==='login'?'PLAYER LOGIN':'PLAYER REGISTRATION'}</h1><span/></div><p className="subtitle">{mode==='login'?'Join the mission. Prove your skills.':'Create your secure player profile.'}</p><Field icon={UserRound} placeholder="Enter your name" value={form.name} onChange={v=>change('name',v)}/><Field icon={GraduationCap} placeholder="Enter your PRN" value={form.prn} onChange={v=>change('prn',v)}/><div className="field"><Building2/><select value={form.branch} onChange={e=>change('branch',e.target.value)}><option value="">Select your Engineering Branch</option>{BRANCHES.map(b=><option key={b} value={b}>{b}</option>)}</select></div><Field icon={LockKeyhole} type="password" placeholder="Enter access password (6+ chars)" value={form.password} onChange={v=>change('password',v)}/>{error&&<div className="login-error">{error}</div>}<button className="enter" disabled={busy}>{busy?'AUTHENTICATING...':mode==='login'?'ENTER GAME':'CREATE PLAYER'} <ArrowRight size={23}/></button><div className="switch">{mode==='login'?<>New player? <button type="button" onClick={()=>setMode('register')}>Create profile</button></>:<>Already registered? <button type="button" onClick={()=>setMode('login')}>Login</button></>}</div><div className="secure"><ShieldCheck size={14}/> PASSWORDS ARE HASHED • RESULTS STORED SERVER-SIDE</div></form><aside className="login-right"><div className="future">A SAFER<br/>DIGITAL<br/>WORLD</div><div className="tower">◈</div><b>SMALL ACTIONS<br/>BIG SECURITY</b><p>CYBER SECURITY<br/>OUR SHARED<br/>RESPONSIBILITY</p></aside></section><footer>STUDENTS TODAY &nbsp; | &nbsp; SECURE TOMORROW <span>TECH RUNNER v1.0</span></footer></main>}
function Field({icon:Icon,type='text',placeholder,value,onChange}){return <div className="field"><Icon/><input type={type} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)} autoComplete={type==='password'?'current-password':'off'}/></div>}
