import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Trophy, RotateCcw, Medal } from 'lucide-react';
import { getGameSession, getScores, createGameSession } from '../../services/gameService';
import { storage } from '../../utils/storage';
import { LEVELS } from '../../utils/constants';
import './FinalResults.css';
export default function FinalResults(){const nav=useNavigate();const [session,setSession]=useState(null);const [scores,setScores]=useState([]);const [error,setError]=useState('');useEffect(()=>{Promise.all([getGameSession(),getScores()]).then(([s,sc])=>{setSession(s);setScores(sc)}).catch(e=>setError(e.message))},[]);const map=Object.fromEntries(scores.map(s=>[s.level,s]));const replay=async()=>{try{const s=await createGameSession();setSession(s);setScores([]);nav('/levels')}catch(e){setError(e.message)}};return <main className="results page"><div className="results-card panel"><div className="result-top"><div className="section-title">MISSION COMPLETE</div><Trophy size={54}/></div><h1>CYBERSECURITY COMPLETE</h1><div className="boss-banner"><Medal/> BOSS DEFEATED <Medal/></div><div className="player-line"><b>{storage.getPlayer()?.name}</b><span>{storage.getPlayer()?.branch}</span></div><div className="result-grid">{LEVELS.map(l=><div className="result-level" key={l.key}><small>{l.short}</small><b>{map[l.key]?.score||0}</b><span>{map[l.key]?.coins||0} COINS</span><span>{formatTime(map[l.key]?.time||0)} • {Math.round(map[l.key]?.distance||0)}m</span></div>)}</div><div className="totals"><div><span>TOTAL SCORE</span><b>{session?.totalScore||0}</b></div><div><span>TOTAL COINS</span><b>{session?.totalCoins||0}</b></div><div><span>TOTAL TIME</span><b>{formatTime(session?.totalTime||0)}</b></div><div><span>TOTAL DISTANCE</span><b>{((session?.totalDistance||0)/1000).toFixed(1)} km</b></div><div><span>OBSTACLES HIT</span><b>{session?.totalObstaclesHit||0}</b></div><div><span>LIVES REMAINING</span><b>{map.cyber?.livesRemaining??0}</b></div></div>{error&&<div className="result-error">{error}</div>}<div className="result-actions"><button onClick={()=>nav('/leaderboard')}>VIEW LEADERBOARD</button><button className="secondary" onClick={replay}><RotateCcw size={16}/> PLAY AGAIN</button></div></div></main>}
function formatTime(s){const sec=Math.round(Number(s)||0);return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
